[host]
name = "portfolio"
domain = "kushalparekh.com"
email = "parekhkushal17@gmail.com"

[source]
branch = "main"

[deploy]
build_command = "npm install . && npm run build"
publish_directory = "dist"
